version: "3"

services:
  app:
    build: .
    image: custom-apt-cacher-ng
    container_name: apt-cacher-ng
    restart: unless-stopped
    ports:
      - 0.0.0.0:3142:3142
    volumes:
      - /var/cache/apt-cacher-ng